export type SkillGroup =
  | 'Languages'
  | 'Frontend'
  | 'Backend'
  | 'Database'
  | 'DevOps / Cloud'
  | 'Testing'
  | 'ML / Data Science'
  | 'Game Dev'
  | 'Tools';

export interface Skill {
  slug: string;
  label: string;
  group: SkillGroup;
}

export const SKILL_GROUPS: SkillGroup[] = [
  'Languages',
  'Frontend',
  'Backend',
  'Database',
  'DevOps / Cloud',
  'Testing',
  'ML / Data Science',
  'Game Dev',
  'Tools',
];

export const SKILLS: Skill[] = [
  // Languages
  { slug: 'c', label: 'C', group: 'Languages' },
  { slug: 'cpp', label: 'C++', group: 'Languages' },
  { slug: 'cs', label: 'C#', group: 'Languages' },
  { slug: 'java', label: 'Java', group: 'Languages' },
  { slug: 'py', label: 'Python', group: 'Languages' },
  { slug: 'js', label: 'JavaScript', group: 'Languages' },
  { slug: 'ts', label: 'TypeScript', group: 'Languages' },
  { slug: 'go', label: 'Go', group: 'Languages' },
  { slug: 'rust', label: 'Rust', group: 'Languages' },
  { slug: 'php', label: 'PHP', group: 'Languages' },
  { slug: 'ruby', label: 'Ruby', group: 'Languages' },
  { slug: 'swift', label: 'Swift', group: 'Languages' },
  { slug: 'kotlin', label: 'Kotlin', group: 'Languages' },
  { slug: 'dart', label: 'Dart', group: 'Languages' },
  { slug: 'scala', label: 'Scala', group: 'Languages' },
  { slug: 'elixir', label: 'Elixir', group: 'Languages' },
  { slug: 'clojure', label: 'Clojure', group: 'Languages' },
  { slug: 'haskell', label: 'Haskell', group: 'Languages' },
  { slug: 'ocaml', label: 'OCaml', group: 'Languages' },
  { slug: 'lua', label: 'Lua', group: 'Languages' },
  { slug: 'perl', label: 'Perl', group: 'Languages' },
  { slug: 'r', label: 'R', group: 'Languages' },
  { slug: 'matlab', label: 'MATLAB', group: 'Languages' },
  { slug: 'fortran', label: 'Fortran', group: 'Languages' },
  { slug: 'crystal', label: 'Crystal', group: 'Languages' },
  { slug: 'nim', label: 'Nim', group: 'Languages' },
  { slug: 'zig', label: 'Zig', group: 'Languages' },
  { slug: 'v', label: 'V', group: 'Languages' },
  { slug: 'vala', label: 'Vala', group: 'Languages' },
  { slug: 'forth', label: 'Forth', group: 'Languages' },
  { slug: 'haxe', label: 'Haxe', group: 'Languages' },
  { slug: 'solidity', label: 'Solidity', group: 'Languages' },
  { slug: 'coffeescript', label: 'CoffeeScript', group: 'Languages' },
  { slug: 'html', label: 'HTML', group: 'Languages' },
  { slug: 'css', label: 'CSS', group: 'Languages' },
  { slug: 'bash', label: 'Bash', group: 'Languages' },
  { slug: 'powershell', label: 'PowerShell', group: 'Languages' },
  { slug: 'latex', label: 'LaTeX', group: 'Languages' },
  { slug: 'md', label: 'Markdown', group: 'Languages' },
  { slug: 'regex', label: 'Regex', group: 'Languages' },
  { slug: 'wasm', label: 'WebAssembly', group: 'Languages' },
  { slug: 'pkl', label: 'Pkl', group: 'Languages' },
  // Frontend
  { slug: 'react', label: 'React', group: 'Frontend' },
  { slug: 'nextjs', label: 'Next.js', group: 'Frontend' },
  { slug: 'vue', label: 'Vue.js', group: 'Frontend' },
  { slug: 'nuxtjs', label: 'Nuxt.js', group: 'Frontend' },
  { slug: 'angular', label: 'Angular', group: 'Frontend' },
  { slug: 'svelte', label: 'Svelte', group: 'Frontend' },
  { slug: 'astro', label: 'Astro', group: 'Frontend' },
  { slug: 'remix', label: 'Remix', group: 'Frontend' },
  { slug: 'solidjs', label: 'SolidJS', group: 'Frontend' },
  { slug: 'gatsby', label: 'Gatsby', group: 'Frontend' },
  { slug: 'ember', label: 'Ember', group: 'Frontend' },
  { slug: 'lit', label: 'Lit', group: 'Frontend' },
  { slug: 'alpinejs', label: 'Alpine.js', group: 'Frontend' },
  { slug: 'htmx', label: 'HTMX', group: 'Frontend' },
  { slug: 'jquery', label: 'jQuery', group: 'Frontend' },
  { slug: 'yew', label: 'Yew', group: 'Frontend' },
  { slug: 'reactivex', label: 'ReactiveX', group: 'Frontend' },
  { slug: 'tailwind', label: 'Tailwind CSS', group: 'Frontend' },
  { slug: 'sass', label: 'Sass', group: 'Frontend' },
  { slug: 'less', label: 'Less', group: 'Frontend' },
  { slug: 'bootstrap', label: 'Bootstrap', group: 'Frontend' },
  { slug: 'materialui', label: 'Material UI', group: 'Frontend' },
  { slug: 'vuetify', label: 'Vuetify', group: 'Frontend' },
  { slug: 'windicss', label: 'WindiCSS', group: 'Frontend' },
  { slug: 'styledcomponents', label: 'Styled Components', group: 'Frontend' },
  { slug: 'emotion', label: 'Emotion', group: 'Frontend' },
  { slug: 'redux', label: 'Redux', group: 'Frontend' },
  { slug: 'pinia', label: 'Pinia', group: 'Frontend' },
  { slug: 'threejs', label: 'Three.js', group: 'Frontend' },
  { slug: 'd3', label: 'D3.js', group: 'Frontend' },
  { slug: 'p5js', label: 'p5.js', group: 'Frontend' },
  { slug: 'svg', label: 'SVG', group: 'Frontend' },
  { slug: 'pug', label: 'Pug', group: 'Frontend' },
  { slug: 'vite', label: 'Vite', group: 'Frontend' },
  { slug: 'webpack', label: 'Webpack', group: 'Frontend' },
  { slug: 'rollupjs', label: 'Rollup.js', group: 'Frontend' },
  { slug: 'babel', label: 'Babel', group: 'Frontend' },
  { slug: 'gulp', label: 'Gulp', group: 'Frontend' },
  { slug: 'electron', label: 'Electron', group: 'Frontend' },
  { slug: 'tauri', label: 'Tauri', group: 'Frontend' },
  { slug: 'flutter', label: 'Flutter', group: 'Frontend' },
  { slug: 'qt', label: 'Qt', group: 'Frontend' },
  { slug: 'gtk', label: 'GTK', group: 'Frontend' },
  // Backend
  { slug: 'nodejs', label: 'Node.js', group: 'Backend' },
  { slug: 'bun', label: 'Bun', group: 'Backend' },
  { slug: 'deno', label: 'Deno', group: 'Backend' },
  { slug: 'express', label: 'Express', group: 'Backend' },
  { slug: 'nestjs', label: 'NestJS', group: 'Backend' },
  { slug: 'adonis', label: 'AdonisJS', group: 'Backend' },
  { slug: 'elysia', label: 'Elysia', group: 'Backend' },
  { slug: 'fastapi', label: 'FastAPI', group: 'Backend' },
  { slug: 'django', label: 'Django', group: 'Backend' },
  { slug: 'flask', label: 'Flask', group: 'Backend' },
  { slug: 'rails', label: 'Rails', group: 'Backend' },
  { slug: 'spring', label: 'Spring', group: 'Backend' },
  { slug: 'dotnet', label: '.NET', group: 'Backend' },
  { slug: 'laravel', label: 'Laravel', group: 'Backend' },
  { slug: 'symfony', label: 'Symfony', group: 'Backend' },
  { slug: 'actix', label: 'Actix', group: 'Backend' },
  { slug: 'rocket', label: 'Rocket', group: 'Backend' },
  { slug: 'ktor', label: 'Ktor', group: 'Backend' },
  { slug: 'hibernate', label: 'Hibernate', group: 'Backend' },
  { slug: 'graphql', label: 'GraphQL', group: 'Backend' },
  { slug: 'apollo', label: 'Apollo', group: 'Backend' },
  { slug: 'discordjs', label: 'Discord.js', group: 'Backend' },
  { slug: 'prisma', label: 'Prisma', group: 'Backend' },
  { slug: 'sequelize', label: 'Sequelize', group: 'Backend' },
  { slug: 'appwrite', label: 'Appwrite', group: 'Backend' },
  // Database
  { slug: 'postgres', label: 'PostgreSQL', group: 'Database' },
  { slug: 'mysql', label: 'MySQL', group: 'Database' },
  { slug: 'sqlite', label: 'SQLite', group: 'Database' },
  { slug: 'mongodb', label: 'MongoDB', group: 'Database' },
  { slug: 'redis', label: 'Redis', group: 'Database' },
  { slug: 'cassandra', label: 'Cassandra', group: 'Database' },
  { slug: 'dynamodb', label: 'DynamoDB', group: 'Database' },
  { slug: 'elasticsearch', label: 'Elasticsearch', group: 'Database' },
  { slug: 'supabase', label: 'Supabase', group: 'Database' },
  { slug: 'firebase', label: 'Firebase', group: 'Database' },
  { slug: 'planetscale', label: 'PlanetScale', group: 'Database' },
  // DevOps / Cloud
  { slug: 'git', label: 'Git', group: 'DevOps / Cloud' },
  { slug: 'github', label: 'GitHub', group: 'DevOps / Cloud' },
  { slug: 'gitlab', label: 'GitLab', group: 'DevOps / Cloud' },
  { slug: 'bitbucket', label: 'Bitbucket', group: 'DevOps / Cloud' },
  { slug: 'githubactions', label: 'GitHub Actions', group: 'DevOps / Cloud' },
  { slug: 'docker', label: 'Docker', group: 'DevOps / Cloud' },
  { slug: 'kubernetes', label: 'Kubernetes', group: 'DevOps / Cloud' },
  { slug: 'terraform', label: 'Terraform', group: 'DevOps / Cloud' },
  { slug: 'ansible', label: 'Ansible', group: 'DevOps / Cloud' },
  { slug: 'jenkins', label: 'Jenkins', group: 'DevOps / Cloud' },
  { slug: 'nginx', label: 'Nginx', group: 'DevOps / Cloud' },
  { slug: 'kafka', label: 'Kafka', group: 'DevOps / Cloud' },
  { slug: 'rabbitmq', label: 'RabbitMQ', group: 'DevOps / Cloud' },
  { slug: 'aws', label: 'AWS', group: 'DevOps / Cloud' },
  { slug: 'gcp', label: 'GCP', group: 'DevOps / Cloud' },
  { slug: 'azure', label: 'Azure', group: 'DevOps / Cloud' },
  { slug: 'vercel', label: 'Vercel', group: 'DevOps / Cloud' },
  { slug: 'cloudflare', label: 'Cloudflare', group: 'DevOps / Cloud' },
  { slug: 'workers', label: 'CF Workers', group: 'DevOps / Cloud' },
  { slug: 'netlify', label: 'Netlify', group: 'DevOps / Cloud' },
  { slug: 'heroku', label: 'Heroku', group: 'DevOps / Cloud' },
  { slug: 'openshift', label: 'OpenShift', group: 'DevOps / Cloud' },
  { slug: 'openstack', label: 'OpenStack', group: 'DevOps / Cloud' },
  { slug: 'grafana', label: 'Grafana', group: 'DevOps / Cloud' },
  { slug: 'prometheus', label: 'Prometheus', group: 'DevOps / Cloud' },
  { slug: 'sentry', label: 'Sentry', group: 'DevOps / Cloud' },
  { slug: 'linux', label: 'Linux', group: 'DevOps / Cloud' },
  { slug: 'ubuntu', label: 'Ubuntu', group: 'DevOps / Cloud' },
  { slug: 'debian', label: 'Debian', group: 'DevOps / Cloud' },
  { slug: 'redhat', label: 'Red Hat', group: 'DevOps / Cloud' },
  { slug: 'arch', label: 'Arch Linux', group: 'DevOps / Cloud' },
  { slug: 'kali', label: 'Kali Linux', group: 'DevOps / Cloud' },
  { slug: 'mint', label: 'Linux Mint', group: 'DevOps / Cloud' },
  { slug: 'bsd', label: 'BSD', group: 'DevOps / Cloud' },
  { slug: 'nix', label: 'Nix', group: 'DevOps / Cloud' },
  { slug: 'windows', label: 'Windows', group: 'DevOps / Cloud' },
  // Testing
  { slug: 'jest', label: 'Jest', group: 'Testing' },
  { slug: 'vitest', label: 'Vitest', group: 'Testing' },
  { slug: 'cypress', label: 'Cypress', group: 'Testing' },
  { slug: 'selenium', label: 'Selenium', group: 'Testing' },
  { slug: 'gherkin', label: 'Gherkin', group: 'Testing' },
  // ML / Data Science
  { slug: 'pytorch', label: 'PyTorch', group: 'ML / Data Science' },
  { slug: 'tensorflow', label: 'TensorFlow', group: 'ML / Data Science' },
  { slug: 'sklearn', label: 'Scikit-learn', group: 'ML / Data Science' },
  { slug: 'opencv', label: 'OpenCV', group: 'ML / Data Science' },
  { slug: 'anaconda', label: 'Anaconda', group: 'ML / Data Science' },
  { slug: 'octave', label: 'Octave', group: 'ML / Data Science' },
  // Game Dev
  { slug: 'unity', label: 'Unity', group: 'Game Dev' },
  { slug: 'unreal', label: 'Unreal Engine', group: 'Game Dev' },
  { slug: 'godot', label: 'Godot', group: 'Game Dev' },
  { slug: 'bevy', label: 'Bevy', group: 'Game Dev' },
  { slug: 'gamemakerstudio', label: 'GameMaker Studio', group: 'Game Dev' },
  { slug: 'haxeflixel', label: 'HaxeFlixel', group: 'Game Dev' },
  { slug: 'robloxstudio', label: 'Roblox Studio', group: 'Game Dev' },
  { slug: 'processing', label: 'Processing', group: 'Game Dev' },
  // Tools
  { slug: 'vscode', label: 'VS Code', group: 'Tools' },
  { slug: 'vscodium', label: 'VSCodium', group: 'Tools' },
  { slug: 'visualstudio', label: 'Visual Studio', group: 'Tools' },
  { slug: 'neovim', label: 'Neovim', group: 'Tools' },
  { slug: 'vim', label: 'Vim', group: 'Tools' },
  { slug: 'emacs', label: 'Emacs', group: 'Tools' },
  { slug: 'idea', label: 'IntelliJ IDEA', group: 'Tools' },
  { slug: 'webstorm', label: 'WebStorm', group: 'Tools' },
  { slug: 'pycharm', label: 'PyCharm', group: 'Tools' },
  { slug: 'clion', label: 'CLion', group: 'Tools' },
  { slug: 'rider', label: 'Rider', group: 'Tools' },
  { slug: 'phpstorm', label: 'PhpStorm', group: 'Tools' },
  { slug: 'eclipse', label: 'Eclipse', group: 'Tools' },
  { slug: 'androidstudio', label: 'Android Studio', group: 'Tools' },
  { slug: 'sublime', label: 'Sublime Text', group: 'Tools' },
  { slug: 'atom', label: 'Atom', group: 'Tools' },
  { slug: 'npm', label: 'npm', group: 'Tools' },
  { slug: 'pnpm', label: 'pnpm', group: 'Tools' },
  { slug: 'yarn', label: 'Yarn', group: 'Tools' },
  { slug: 'gradle', label: 'Gradle', group: 'Tools' },
  { slug: 'maven', label: 'Maven', group: 'Tools' },
  { slug: 'cmake', label: 'CMake', group: 'Tools' },
  { slug: 'postman', label: 'Postman', group: 'Tools' },
  { slug: 'figma', label: 'Figma', group: 'Tools' },
  { slug: 'xd', label: 'Adobe XD', group: 'Tools' },
  { slug: 'blender', label: 'Blender', group: 'Tools' },
  { slug: 'arduino', label: 'Arduino', group: 'Tools' },
  { slug: 'raspberrypi', label: 'Raspberry Pi', group: 'Tools' },
  { slug: 'ros', label: 'ROS', group: 'Tools' },
];

export const SKILL_MAP: Record<string, Skill> = Object.fromEntries(SKILLS.map((s) => [s.slug, s]));

export const SKILLS_BY_GROUP: Record<SkillGroup, Skill[]> = Object.fromEntries(
  SKILL_GROUPS.map((g) => [g, SKILLS.filter((s) => s.group === g)]),
) as Record<SkillGroup, Skill[]>;
